all:
	pandoc concurso.md -s -o concurso169.pdf -t beamer -V aspectratio=169 -V theme=Warsaw -V fontsize=8pt -f markdown+implicit_figures
	#pandoc concurso.md -s -o concurso43.pdf -t beamer -V aspectratio=43 -V fontsize=8pt -f markdown+implicit_figures
	#pandoc concurso.md -s -o concurso169nh.pdf -t beamer -V aspectratio=169 -V theme=Warsaw -V fontsize=9pt --no-highlight -f markdown+implicit_figures
	#pandoc concurso.md -s -o concurso43nh.pdf -t beamer -V aspectratio=43 -V fontsize=8pt --no-highlight -f markdown+implicit_figures
